name: fertilefuture
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  http: ^1.1.0
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.3
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  url_launcher: ^6.1.14
  http_parser: ^4.0.2
  convert: ^3.1.1
  flutter_carousel_widget: ^2.2.0
  flutter_blue_plus: ^1.34.5
  # flutter_blue: 
  

dev_dependencies:
  intl_utils: any
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/background.png
    - assets/translations/
    - assets/images/banner1.png
    - assets/images/banner2.png
    - assets/images/banner3.png

